My Project: TaskManager Class Reference
TaskManager Class Reference
#include <t.h>
Public Member Functions
TaskManager (std::vector< std::vector< std::string > > &csvData)
void Print ()
void Graph (std::string &filename)
Task * FindTask (std::string &name)
void IntegrityCheck ()
size_t size ()
Task * getTask (size_t t)
TaskManager (vector< vector< string > > &csvData)
void Print ()
void Graph (string &filename)
Detailed Description
Definition at line 23 of file t.h.
Constructor & Destructor Documentation
TaskManager::TaskManager (std::vector< std::vector< std::string > > & csvData)
Definition at line 64 of file t.cpp.
References Task::Task().
   {
     int lineNumber = 0;
     for(auto row : csvData) {
       try {
         lineNumber++;
         taskList.push_back( move(Task(row)) );
       } catch(std::string& e) {
         cerr << "Problem with line " << lineNumber << ": " << e << "\n";
       }
     }
   }
TaskManager::TaskManager (vector< vector< string > > & csvData) inline
Definition at line 69 of file task.cpp.
   {
     int lineNumber = 0;
     for(auto row : csvData) {
       try {
         lineNumber++;
         taskList.push_back( move(Task(row)) );
       } catch(string& e) {
         cerr << "Problem with line " << lineNumber << ": " << e << "\n";
       }
     }
   }
Member Function Documentation
Task * TaskManager::FindTask (std::string & name)
Definition at line 109 of file t.cpp.
References Task::getTaskName().
Referenced by ItemManager::IntegrityCheck().
   {
     for(size_t t = 0; t < taskList.size(); t++) {
       if(taskList[t].getTaskName() == name)                                       // case matters
       // if(strcasecmp(taskList[t].getTaskName().c_str(),  name.c_str()) == 0)    // if ignoring case
         return &taskList[t];
     }
     return nullptr; // not found
   }
Task* TaskManager::getTask (size_t t) inline
Definition at line 32 of file t.h.
Referenced by Factory::Factory().
 { return &taskList[t]; }
void TaskManager::Graph (std::string & filename)
Definition at line 85 of file t.cpp.
Referenced by main().
   {
     fstream os(filename + ".gv", ios::out);
     if(os.is_open()) {
       os << "digraph taskgraph {\n";
       for(auto t : taskList) {
         t.Graph(os);
       }
       os << "}\n";
       os.close();
       std::string cmd;
       #ifdef __MSVC
         cmd = "C:/\"Program Files (x86)\"/Graphviz2.38/bin/dot.exe"
       #else
         cmd = "dot";
       #endif
       cmd += std::string(" -Tpng ") + filename + ".gv >" +filename + ".gv.png";
       cout << "running " << cmd << "\n";
       cout << "returned " << system(cmd.c_str()) << " <-- 0 is good because it means dot worked!\n";
     }
   }
void TaskManager::Graph (string & filename) inline
Definition at line 90 of file task.cpp.
   {
     fstream os(filename + ".gv", ios::out);
     if(os.is_open()) {
       os << "digraph taskgraph {\n";
       for(auto t : taskList) {
         t.Graph(os);
       }
       os << "}\n";
       os.close();
       string cmd;
       #ifdef __MSVC
         cmd = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe"
       #else
         cmd = "dot";
       #endif
       cmd += string(" -Tpng ") + filename + ".gv >" +filename + ".gv.png";
       cout << "running " << cmd << "\n";
       system(cmd.c_str());
     }
   }
void TaskManager::IntegrityCheck ()
Definition at line 119 of file t.cpp.
Referenced by main().
   {
     for(auto t : taskList) {
       if(not t.getTaskPass().empty() && FindTask(t.getTaskPass()) == nullptr) {
         throw std::string("Task '") + t.getTaskName() + "' references Pass task '" + t.getTaskPass() + "' but it does not exist!";
       }
       if(not t.getTaskFail().empty() && FindTask(t.getTaskFail()) == nullptr) {
         throw std::string("Task '") + t.getTaskName() + "' references Fail task '" + t.getTaskFail() + "' but it does not exist!";
       }
     }
   }
void TaskManager::Print ()
Definition at line 76 of file t.cpp.
Referenced by main().
   {
     int lineNumber = 0;
     for(auto t : taskList) {
         lineNumber++;
         cout << lineNumber << ": ";
         t.Print();
     }
   }
void TaskManager::Print () inline
Definition at line 81 of file task.cpp.
   {
     int lineNumber = 0;
     for(auto t : taskList) {
         lineNumber++;
         cout << lineNumber << ": ";
         t.Print();
     }
   }
size_t TaskManager::size () inline
Definition at line 31 of file t.h.
Referenced by Factory::Factory().
 { return taskList.size(); }
The documentation for this class was generated from the following files:
t.h
task.cpp
t.cpp