My Project: ItemManager Class Reference
ItemManager Class Reference
#include <i.h>
Public Member Functions
ItemManager (vector< vector< string > > &csvData)
void Print ()
void Graph (string &filename)
Item * FindItem (std::string &name)
void IntegrityCheck (TaskManager &tm)
size_t getSize ()
Item * getItem (size_t i)
ItemManager (vector< vector< string > > &csvData)
void Print ()
void Graph (string &filename)
Detailed Description
Definition at line 25 of file i.h.
Constructor & Destructor Documentation
ItemManager::ItemManager (vector< vector< string > > & csvData)
Definition at line 62 of file i.cpp.
   {
     int lineNumber = 0;
     for(auto row : csvData) {
       try {
         lineNumber++;
         itemList.push_back( move(Item(row)) );
       } catch(string& e) {
         cerr << "Problem with line " << lineNumber << ": " << e << "\n";
       }
     }
   }
ItemManager::ItemManager (vector< vector< string > > & csvData) inline
Definition at line 67 of file item.cpp.
   {
     int lineNumber = 0;
     for(auto row : csvData) {
       try {
         lineNumber++;
         itemList.push_back( move(Item(row)) );
       } catch(string& e) {
         cerr << "Problem with line " << lineNumber << ": " << e << "\n";
       }
     }
   }
Member Function Documentation
Item * ItemManager::FindItem (std::string & name)
Definition at line 120 of file i.cpp.
Referenced by Factory::Factory(), and OrderManager::IntegrityCheck().
  {
    for(size_t i = 0 ; itemList.size(); i++) {
      if(itemList[i].getItemName() == name)                                         // if  case matters
       // if(strcasecmp(itemList[i].getItemName() .c_str(),  name.c_str()) == 0)    // if ignoring case
        return &itemList[i];
    }
    return nullptr;
  }
Item* ItemManager::getItem (size_t i) inline
Definition at line 35 of file i.h.
Referenced by Machine::Classify().
 { return &itemList[i]; }
size_t ItemManager::getSize () inline
Definition at line 34 of file i.h.
Referenced by Machine::Classify().
 { return itemList.size(); }
void ItemManager::Graph (string & filename)
Definition at line 83 of file i.cpp.
Referenced by main().
   {
     fstream os(filename + ".gv", ios::out);
     if(os.is_open()) {
       os << "digraph itemgraph {\n";
       for(auto t : itemList) {
         t.Graph(os);
       }
       os << "}\n";
       os.close();
       std::string cmd;
       #ifdef __MSVC
         cmd = "C:/\"Program Files (x86)\"/Graphviz2.38/bin/dot.exe"
       #else
         cmd = "dot";
       #endif
       cmd += std::string(" -Tpng ") + filename + ".gv >" +filename + ".gv.png";
       cout << "running " << cmd << "\n";
       cout << "returned " << system(cmd.c_str()) << " <-- 0 is good because it means dot worked!\n";
     }
   }
void ItemManager::Graph (string & filename) inline
Definition at line 88 of file item.cpp.
   {
     fstream os(filename + ".gv", ios::out);
     if(os.is_open()) {
       os << "digraph itemgraph {\n";
       for(auto t : itemList) {
         t.Graph(os);
       }
       os << "}\n";
       os.close();
       string cmd;
       #ifdef __MSVC
         cmd = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe"
       #else
         cmd = "dot";
       #endif
       cmd += string(" -Tpng ") + filename + ".gv >" +filename + ".gv.png";
       cout << "running " << cmd << "\n";
       system(cmd.c_str());
     }
   }
void ItemManager::IntegrityCheck (TaskManager & tm)
Definition at line 107 of file i.cpp.
References TaskManager::FindTask().
Referenced by main().
   {
     for(auto i : itemList) {
       if(tm.FindTask(i.getItemInstallerTask()) == nullptr) {
         throw std::string("Item '") + i.getItemName() + "' references installer task '" + i.getItemInstallerTask() + "' but it does not exist!";
       }
       if(tm.FindTask(i.getItemRemoverTask()) == nullptr) {
         throw std::string("Item '") + i.getItemName() + "' references remover task '" + i.getItemRemoverTask() + "' but it does not exist!";
       }
     }
   }
void ItemManager::Print ()
Definition at line 74 of file i.cpp.
Referenced by main().
   {
     int lineNumber = 0;
     for(auto t : itemList) {
         lineNumber++;
         cout << lineNumber << ": ";
         t.Print();
     }
   }
void ItemManager::Print () inline
Definition at line 79 of file item.cpp.
   {
     int lineNumber = 0;
     for(auto t : itemList) {
         lineNumber++;
         cout << lineNumber << ": ";
         t.Print();
     }
   }
The documentation for this class was generated from the following files:
i.h
item.cpp
i.cpp