My Project: OrderManager Class Reference
OrderManager Class Reference
#include <o.h>
Public Member Functions
OrderManager (vector< vector< string > > &csvData)
void Print ()
void Graph (string &filename)
void IntegrityCheck (ItemManager &im)
size_t getSize ()
Order * getOrder (size_t o)
OrderManager (vector< vector< string > > &csvData)
void Print ()
void Graph (string &filename)
Detailed Description
Definition at line 27 of file o.h.
Constructor & Destructor Documentation
OrderManager::OrderManager (vector< vector< string > > & csvData)
Definition at line 51 of file o.cpp.
   {
     int lineNumber = 0;
     for(auto row : csvData) {
       try {
         lineNumber++;
         orderList.push_back( move(Order(row)) );
       } catch(string& e) {
         cerr << "Problem with line " << lineNumber << ": " << e << "\n";
       }
     }
   }
OrderManager::OrderManager (vector< vector< string > > & csvData) inline
Definition at line 58 of file order.cpp.
   {
     int lineNumber = 0;
     for(auto row : csvData) {
       try {
         lineNumber++;
         orderList.push_back( move(Order(row)) );
       } catch(string& e) {
         cerr << "Problem with line " << lineNumber << ": " << e << "\n";
       }
     }
   }
Member Function Documentation
Order* OrderManager::getOrder (size_t o) inline
Definition at line 36 of file o.h.
Referenced by Factory::Factory().
 { return &orderList[o]; }
size_t OrderManager::getSize () inline
Definition at line 35 of file o.h.
Referenced by Factory::Factory().
 { return orderList.size(); }
void OrderManager::Graph (string & filename)
Definition at line 72 of file o.cpp.
Referenced by main().
   {
     fstream os(filename + ".gv", ios::out);
     if(os.is_open()) {
       os << "digraph ordergraph {\n";
       for(auto o : orderList) {
         o.Graph(os);
       }
       os << "}\n";
       os.close();
       std::string cmd;
       #ifdef __MSVC
         cmd = "C:/\"Program Files (x86)\"/Graphviz2.38/bin/dot.exe"
       #else
         cmd = "dot";
       #endif
       cmd += std::string(" -Tpng ") + filename + ".gv >" +filename + ".gv.png";
       cout << "running " << cmd << "\n";
       cout << "returned " << system(cmd.c_str()) << " <-- 0 is good because it means dot worked!\n";
     }
   }
void OrderManager::Graph (string & filename) inline
Definition at line 79 of file order.cpp.
   {
     fstream os(filename + ".gv", ios::out);
     if(os.is_open()) {
       os << "digraph ordergraph {\n";
       for(auto t : orderList) {
         t.Graph(os);
       }
       os << "}\n";
       os.close();
       string cmd;
       #ifdef __MSVC
         cmd = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe"
       #else
         cmd = "dot";
       #endif
       cmd += string(" -Tpng ") + filename + ".gv >" +filename + ".gv.png";
       cout << "running " << cmd << "\n";
       system(cmd.c_str());
     }
   }
void OrderManager::IntegrityCheck (ItemManager & im)
Definition at line 96 of file o.cpp.
References ItemManager::FindItem().
Referenced by main().
   {
     for(auto o : orderList) { // for each order
       for(size_t count = 0; count < o.size(); count++) { // for ech item in that order
         if(im.FindItem( o.getItem(count) ) == nullptr) { // throw if not found
           throw std::string("Order '") + o.getCustomer() + "/" + o.getProduct() +
                 "' references item '" + o.getItem(count) + "' but it does not exist!";
         }
       }
     }
   }
void OrderManager::Print ()
Definition at line 63 of file o.cpp.
Referenced by main().
   {
     int lineNumber = 0;
     for(auto t : orderList) {
         lineNumber++;
         cout << lineNumber << ": ";
         t.Print();
     }
   }
void OrderManager::Print () inline
Definition at line 70 of file order.cpp.
   {
     int lineNumber = 0;
     for(auto t : orderList) {
         lineNumber++;
         cout << lineNumber << ": ";
         t.Print();
     }
   }
The documentation for this class was generated from the following files:
o.h
order.cpp
o.cpp