My Project: Order Class Reference
Order Class Reference
#include <o.h>
Public Member Functions
Order ()
Order (vector< string > row)
void Print ()
void Graph (fstream &os)
string & getCustomer ()
string & getProduct ()
size_t size ()
string & getItem (size_t i)
Order (vector< string > row)
void Print ()
void Graph (fstream &os)
Detailed Description
Definition at line 13 of file o.h.
Constructor & Destructor Documentation
Order::Order () inline
Definition at line 17 of file o.h.
 {}
Order::Order (vector< string > row)
Definition at line 11 of file o.cpp.
References validItemName(), validOrderCustomerName(), and validOrderProductName().
   {
     if( row.size()  < 3) {
       throw string("need at least 3 fields, found ") + to_string( row.size() );
     }
     if(validOrderCustomerName( row[0] ))
       orderCustomerName = row[0];
     else
       throw string("expected customer name, found [") + row[0] + "]";
     if(validOrderProductName( row[1] ))
       orderProductName = row[1];
     else
       throw string("expected product name, found [") + row[1] + "]";
     for(size_t i = 2; i < row.size(); i++)
       if(validItemName( row[i] ))
         itemList.push_back( row[i]);
       else
         throw string("expected item name, found [") + row[i] + "]";
   }
Order::Order (vector< string > row) inline
Definition at line 14 of file order.cpp.
References validItemName(), validOrderCustomerName(), and validOrderProductName().
   {
     if( row.size()  < 3) {
       throw string("need at lest 3 fields, found ") + to_string( row.size() );
     }
     if(validOrderCustomerName( row[0] ))
       orderCustomerName = row[0];
     else
       throw string("expected customer name, found [") + row[0] + "]";
     if(validOrderProductName( row[1] ))
       orderProductName = row[1];
     else
       throw string("expected product name, found [") + row[1] + "]";
     for(size_t i = 2; i < row.size(); i++)
       if(validItemName( row[i] ))
         itemList.push_back( row[i]);
       else
         throw string("expected item name, found [") + row[i] + "]";
   }
Member Function Documentation
string& Order::getCustomer () inline
Definition at line 21 of file o.h.
Referenced by Factory::Factory().
 { return orderCustomerName; }
string& Order::getItem (size_t i) inline
Definition at line 24 of file o.h.
Referenced by Factory::Factory().
 { return itemList[i]; }
string& Order::getProduct () inline
Definition at line 22 of file o.h.
Referenced by Factory::Factory().
 { return orderProductName; }
void Order::Graph (fstream & os)
Definition at line 42 of file o.cpp.
   {
       for(auto e : itemList)
         os << '"' << orderCustomerName  << "\n" << orderProductName<< '"'
            << "->"
            << '"' << e << '"'
            << "[color=blue];\n";
   }
void Order::Graph (fstream & os) inline
Definition at line 45 of file order.cpp.
   {
       for(auto e : itemList)
         os << '"' << orderCustomerName  << "\n" << orderProductName<< '"'
            << "->"
            << '"' << e << '"'
            << "[color=blue];\n";
   }
void Order::Print ()
Definition at line 33 of file o.cpp.
   {
     cout << "[" << orderCustomerName << "] "
          << "[" << orderProductName << "] ";
     for(auto e : itemList)
          cout << "[" << e << "] ";
     cout << "\n";
   }
void Order::Print () inline
Definition at line 36 of file order.cpp.
   {
     cout << "[" << orderCustomerName << "] "
          << "[" << orderProductName << "] ";
     for(auto e : itemList)
          cout << "[" << e << "] ";
     cout << "\n";
   }
size_t Order::size () inline
Definition at line 23 of file o.h.
Referenced by Factory::Factory(), and Job::Job().
 { return itemList.size(); }
The documentation for this class was generated from the following files:
o.h
order.cpp
o.cpp