My Project: Task Class Reference
Task Class Reference
#include <t.h>
Public Member Functions
Task ()
Task (std::vector< std::string > row)
void Print ()
void Graph (std::fstream &os)
std::string & getTaskName ()
std::string & getTaskPass ()
std::string & getTaskFail ()
Task (vector< string > row)
void Print ()
void Graph (fstream &os)
Detailed Description
Definition at line 11 of file t.h.
Constructor & Destructor Documentation
Task::Task () inline
Definition at line 14 of file t.h.
References Graph(), and Print().
Referenced by TaskManager::TaskManager().
 {}
Task::Task (std::vector< std::string > row)
Definition at line 12 of file t.cpp.
References validSlotName(), and validTaskName().
     : taskSlots("1")
   {
     switch( row.size() ) {
     case 4:
       if(validTaskName( row[3] ))
         taskFail = row[3];
       else
         throw std::string("expected fail task name, found [") + row[3] + "]";
     case 3:
       if(validTaskName( row[2] ))
         taskPass = row[2];
       else
         throw std::string("expected fail task name, found [") + row[2] + "]";
     case 2:
       if(validSlotName( row[1] ))
         taskSlots = row[1];
       else
         throw std::string("expected fail task name, found [") + row[2] + "]";
     case 1:
       if(validTaskName( row[0] ))
         taskName = row[0];
       else
         throw std::string("expected fail task name, found [") + row[0] + "]";
       break;
     default:
       throw std::string("expected 1,2,3, or 4 fields, found - ") + to_string(row.size());
     }
   }
Task::Task (vector< string > row) inline
Definition at line 13 of file task.cpp.
References validSlotName(), and validTaskName().
     : taskSlots("1")
   {
     switch( row.size() ) {
     case 4:
       if(validTaskName( row[3] ))
         taskFail = row[3];
       else
         throw string("expected fail task name, found [") + row[3] + "]";
     case 3:
       if(validTaskName( row[2] ))
         taskPass = row[2];
       else
         throw string("expected fail task name, found [") + row[2] + "]";
     case 2:
       if(validSlotName( row[1] ))
         taskSlots = row[1];
       else
         throw string("expected fail task name, found [") + row[2] + "]";
     case 1:
       if(validTaskName( row[0] ))
         taskName = row[0];
       else
         throw string("expected fail task name, found [") + row[0] + "]";
       break;
     default:
       throw string("expected 1,2,3, or 4 fields, found - ") + to_string(row.size());
     }
   }
Member Function Documentation
std::string& Task::getTaskFail () inline
Definition at line 20 of file t.h.
 { return taskFail; }
std::string& Task::getTaskName () inline
Definition at line 18 of file t.h.
Referenced by Machine::Classify(), and TaskManager::FindTask().
 { return taskName; }
std::string& Task::getTaskPass () inline
Definition at line 19 of file t.h.
Referenced by Factory::Factory(), and Machine::isSink().
 { return taskPass; }
void Task::Graph (std::fstream & os)
Referenced by Print(), and Task().
void Task::Graph (fstream & os) inline
Definition at line 49 of file task.cpp.
   {
     if(not taskFail.empty() )
       os << '"' << taskName << '"'
          << "->"
          << '"' << taskFail << '"'
          << "[color=red];\n";
     if(not taskPass.empty() )
       os << '"' << taskName << '"' \
          << "->" << '"' << taskPass << '"' \
          << "[color=green];\n";
     if(taskFail.empty() and taskPass.empty() )
       os << '"' << taskName << '"'
          << ";\n";
   }
void Task::Print ()
Definition at line 41 of file t.cpp.
References Graph().
Referenced by Task().
   {
     cout << "[" << taskName << "] "
          << "[" << taskSlots << "] "
          << "[" << taskPass << "] "
          << "[" << taskFail << "]\n";
   }
void Task::Print () inline
Definition at line 42 of file task.cpp.
   {
     cout << "[" << taskName << "] "
          << "[" << taskSlots << "] "
          << "[" << taskPass << "] "
          << "[" << taskFail << "]\n";
   }
The documentation for this class was generated from the following files:
t.h
task.cpp
t.cpp