My Project: Item Class Reference
Item Class Reference
#include <i.h>
Public Member Functions
Item (vector< string > row)
void Print ()
void Graph (fstream &os)
std::string & getItemName ()
std::string & getItemInstallerTask ()
std::string & getItemRemoverTask ()
Item (vector< string > row)
void Print ()
void Graph (fstream &os)
Detailed Description
Definition at line 13 of file i.h.
Constructor & Destructor Documentation
Item::Item (vector< string > row)
Definition at line 12 of file i.cpp.
References validItemName(), validItemSequence(), and validTaskName().
   {
     switch( row.size() ) {
     case 5:
       itemDescription = row[4];
     case 4:
       if(validItemSequence( row[3] ))
         itemSequence = row[3];
       else
         throw string("expected sequence, found [") + row[3] + "]";
     // case 3:
       if(validTaskName( row[2] ))
         itemRemoverTask = row[2];
       else
         throw string("expected fail item name, found [") + row[2] + "]";
     // case 2:
       if(validTaskName( row[1] ))
         itemInstallerTask = row[1];
       else
         throw string("expected fail item name, found [") + row[1] + "]";
     // case 1:
       if(validItemName( row[0] ))
         itemName = row[0];
       else
         throw string("expected fail item name, found [") + row[0] + "]";
       break;
     default:
       throw string("expected 4 or 5 fields, found - ") + to_string(row.size());
     }
   }
Item::Item (vector< string > row) inline
Definition at line 13 of file item.cpp.
References validItemName(), validItemSequence(), and validTaskName().
   {
     switch( row.size() ) {
     case 5:
       itemDescription = row[4];
     case 4:
       if(validItemSequence( row[3] ))
         itemSequence = row[3];
       else
         throw string("expected sequence, found [") + row[3] + "]";
     // case 3:
       if(validTaskName( row[2] ))
         itemRemoverTask = row[2];
       else
         throw string("expected fail item name, found [") + row[2] + "]";
     // case 2:
       if(validTaskName( row[1] ))
         itemInstallerTask = row[1];
       else
         throw string("expected fail item name, found [") + row[1] + "]";
     // case 1:
       if(validItemName( row[0] ))
         itemName = row[0];
       else
         throw string("expected fail item name, found [") + row[0] + "]";
       break;
     default:
       throw string("expected 4 or 5 fields, found - ") + to_string(row.size());
     }
   }
Member Function Documentation
std::string& Item::getItemInstallerTask () inline
Definition at line 20 of file i.h.
Referenced by Factory::Factory().
 { return itemInstallerTask; }
std::string& Item::getItemName () inline
Definition at line 19 of file i.h.
 { return itemName; }
std::string& Item::getItemRemoverTask () inline
Definition at line 21 of file i.h.
Referenced by Factory::Factory().
 { return itemRemoverTask; }
void Item::Graph (fstream & os)
Definition at line 50 of file i.cpp.
   {
       os << '"' << "Item\n" << itemName << '"'
          << "->"
          << '"' << "Installer\n" << itemInstallerTask << '"'
          << "[color=green];\n";
       os << '"' << "Item\n" << itemName << '"' \
          << "->" << '"' << "Remover\n" << itemRemoverTask << '"' \
          << "[color=red];\n";
   }
void Item::Graph (fstream & os) inline
Definition at line 51 of file item.cpp.
   {
       os << '"' << "Item\n" << itemName << '"'
          << "->"
          << '"' << "Installer\n" << itemInstallerTask << '"'
          << "[color=green];\n";
       os << '"' << "Item\n" << itemName << '"' \
          << "->" << '"' << "Remover\n" << itemRemoverTask << '"' \
          << "[color=red];\n";
   }
void Item::Print ()
Definition at line 42 of file i.cpp.
   {
     cout << "[" << itemName << "] "
          << "[" << itemInstallerTask << "] "
          << "[" << itemRemoverTask << "] "
          << "[" << itemSequence << "] "
          << "[" << itemDescription << "]\n";
   }
void Item::Print () inline
Definition at line 43 of file item.cpp.
   {
     cout << "[" << itemName << "] "
          << "[" << itemInstallerTask << "] "
          << "[" << itemRemoverTask << "] "
          << "[" << itemSequence << "] "
          << "[" << itemDescription << "]\n";
   }
The documentation for this class was generated from the following files:
i.h
item.cpp
i.cpp