My Project: Machine Class Reference
Machine Class Reference
#include <machine.h>
Public Member Functions
Machine ()
Machine (Task *t)
void IncInComing ()
bool isSource () const
bool isSink ()
bool isSingleton ()
void AddJob (Job job)
size_t inputQSize () const
Job getJob ()
void Classify (ItemManager &im)
bool getInstaller () const
bool getRemover () const
Public Member Functions inherited from Task
Task ()
Task (std::vector< std::string > row)
void Print ()
void Graph (std::fstream &os)
std::string & getTaskName ()
std::string & getTaskPass ()
std::string & getTaskFail ()
Task (vector< string > row)
void Print ()
void Graph (fstream &os)
Detailed Description
Definition at line 8 of file machine.h.
Constructor & Destructor Documentation
Machine::Machine () inline
Definition at line 16 of file machine.h.
     : inComing(0)
   {
   }
Machine::Machine (Task * t) inline
Definition at line 20 of file machine.h.
     : Task(*t)
     , inComing(0)
   {
   }
Member Function Documentation
void Machine::AddJob (Job job) inline
Definition at line 33 of file machine.h.
 { inputQ.push( move ( job ) ); }
void Machine::Classify (ItemManager & im) inline
Definition at line 45 of file machine.h.
References ItemManager::getItem(), ItemManager::getSize(), and Task::getTaskName().
{
     bInstaller = false;
     bRemover   = false;
     for(size_t i = 0; i < im.getSize(); i++ ) {
       if(getTaskName() == im.getItem(i) -> getItemInstallerTask() )
         bInstaller = true;
       if(getTaskName() == im.getItem(i) -> getItemRemoverTask() )
         bRemover = true;
     }
     if(bInstaller) cout << getTaskName() << " is an installer\n";
     if(bRemover)   cout << getTaskName() << " is a remover\n";
     if(bInstaller && bRemover)
       throw getTaskName() + " is BOTH an and a remover";
   }
bool Machine::getInstaller () const inline
Definition at line 62 of file machine.h.
 { return bInstaller; }
Job Machine::getJob () inline
Definition at line 37 of file machine.h.
                {
     //  cout << "getJob: " << inputQSize() << "\n";
     Job job = move( inputQ.front() );
     inputQ.pop();
     //  cout << "getJob after pop: " << inputQSize() << "\n";
     return job;
   }
bool Machine::getRemover () const inline
Definition at line 63 of file machine.h.
 { return bRemover; }
void Machine::IncInComing () inline
Definition at line 25 of file machine.h.
   {
     inComing++;
   }
size_t Machine::inputQSize () const inline
Definition at line 35 of file machine.h.
 { return inputQ.size(); }
bool Machine::isSingleton () inline
Definition at line 31 of file machine.h.
References isSink(), and isSource().
 { return isSource() && isSink(); }  // compiler error if const
bool Machine::isSink () inline
Definition at line 30 of file machine.h.
References Task::getTaskPass().
Referenced by isSingleton().
 { return getTaskPass().empty();  }  // compiler error if const
bool Machine::isSource () const inline
Definition at line 29 of file machine.h.
Referenced by isSingleton().
 { return inComing == 0; }
The documentation for this class was generated from the following file:
machine.h