My Project: order.cpp File Reference
order.cpp File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include "util.h"
Classes
class Order
class OrderManager
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 105 of file order.cpp.
References csvRead(), OrderManager::Graph(), and OrderManager::Print().
 {
   try {
     if(argc != 3) {
       throw string("Usage ") + argv[0] + string(": filename delimiter-char");
     }
     string filename  = string(argv[1]);     // 1st arg is filename
     char   delimiter = argv[2][0];  // 2nd arg, 1st char is delimiter
     vector < vector< string > > csvOrderData;
     csvRead(filename, delimiter, csvOrderData);
     // csvPrint(csvOrderData);
     OrderManager om(csvOrderData);
     om.Print();
     om.Graph(filename);
   } catch (const string& e) {
     cerr << e << "\n";
   }
 }