My Project: task.cpp File Reference
task.cpp File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include "util.h"
Classes
class Task
class TaskManager
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 116 of file task.cpp.
References csvRead(), TaskManager::Graph(), and TaskManager::Print().
 {
   try {
     if(argc != 3) {
       throw string("Usage ") + argv[0] + string(": filename delimiter-char");
     }
     string filename  = string(argv[1]);     // 1st arg is filename
     char   delimiter = argv[2][0];  // 2nd arg, 1st char is delimiter
     vector < vector< string > > csvTaskData;
     csvRead(filename, delimiter, csvTaskData);
     // csvPrint(csvTaskData);
     TaskManager tm(csvTaskData);
     tm.Print();
     tm.Graph(filename);
   } catch (const string& e) {
     cerr << e << "\n";
   }
 }