My Project: util.h File Reference
util.h File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
Functions
void trim (string &s)
void csvPrint (vector< vector< string > > &csvData)
void csvRead (string &filename, char delimiter, vector< vector< string > > &csvData)
bool validItemName (string &t)
bool validItemSequence (string &t)
bool validOrderCustomerName (string &t)
bool validOrderProductName (string &t)
bool validTaskName (string &t)
bool validSlotName (string &t)
Function Documentation
void csvPrint (vector< vector< string > > & csvData)
Definition at line 16 of file csvread.cpp.
Referenced by main().
 {
   cout << "\nindex [] print\n";
   for(size_t row = 0; row < csvData.size(); row++) {
     cout << "row " << row << " ";
     cout << "(" << csvData[row].size() << " fields) ";
     for(size_t column = 0; column < csvData[row].size(); column++) {
       cout << "[" << csvData[row][column] << "] ";
     }
     cout << "\n";
   }
   cout << "\niterator print\n";
   for(auto rowIt = csvData.begin(); rowIt != csvData.end(); rowIt++) {
     cout << "row " << rowIt - csvData.begin() << " ";
     cout << "(" << rowIt -> size() << " fields) ";
     for(auto columnIt = rowIt->begin(); columnIt != rowIt->end(); columnIt++) {
       cout << "{" << *columnIt << "} ";
     }
     cout << "\n";
   }
   cout << "\nrange-based for print\n";
   for(auto row : csvData) {
     cout << "(" << row.size() << " fields) ";
     for(auto column : row) {
       cout << "<" << column << "> ";
     }
     cout << "\n";
   }
 }
void csvRead (string & filename, char delimiter, vector< vector< string > > & csvData)
Definition at line 49 of file csvread.cpp.
References trim().
Referenced by main().
 {
   fstream is( filename, ios::in);
   if( not is.is_open())
     throw string("Canot open file ") + filename ;
   string line;
   while( getline(is, line)) {
     auto cr = line.find('\r');
     if(cr != string::npos)
       line.erase(cr);
     cout << "line -->" << line << "<--\n";
     vector <string> fields;
     string field;
     size_t i = 0;
     while(i < line.size() ) {
       if(line[i] != delimiter) {
         field += line[i];
       } else {
         trim( field );
         fields.push_back( move(field) );
       }
       i++;
     }
     // what if the last entry was not a 'delimiter' character?
     if( not field.empty()) {
       trim( field );
       fields.push_back( move(field) );
     }
     csvData.push_back( move(fields) );
   }
   is.close();
 }
void trim (string & s)
Definition at line 8 of file csvread.cpp.
Referenced by csvRead().
 {
   while(s.size() > 0 && s[0] == ' ')  // kill leading spaces
      s.erase(0,1);
   while(s.size() > 0 && s[s.size()-1] == ' ')  // kill leading spaces
      s.erase(s.size()-1,1);
 }
bool validItemName (string & t)
Definition at line 89 of file util.cpp.
Referenced by Item::Item(), and Order::Order().
 {
   if(t.empty()) return false;
   for(auto c : t) {
     if(not (isalnum(c) || c == ' ' || c == '_') )
       return false;
   }
   return true;
 }
bool validItemSequence (string & t)
Definition at line 100 of file util.cpp.
Referenced by Item::Item().
 {
   if(t.empty()) return false;
   for(auto c : t) {
     if(not isdigit(c))
       return false;
   }
   return true;
 }
bool validOrderCustomerName (string & t)
Definition at line 111 of file util.cpp.
Referenced by Order::Order().
 {
   if(t.empty()) return false;
   for(auto c : t) {
     if(not (isalnum(c) || c == ' ' || c == '\'' || c == '-') )
       return false;
   }
   return true;
 }
bool validOrderProductName (string & t)
Definition at line 122 of file util.cpp.
Referenced by Order::Order().
 {
   if(t.empty()) return false;
   for(auto c : t) {
     if(not (isalnum(c) || c == ' ' || c == '_') )
       return false;
   }
   return true;
 }
bool validSlotName (string & t)
Definition at line 144 of file util.cpp.
Referenced by Task::Task().
 {
   if(t.empty()) return false;
   for(auto c : t) {
     if(not isdigit(c))
       return false;
   }
   return true;
 }
bool validTaskName (string & t)
Definition at line 133 of file util.cpp.
Referenced by Item::Item(), and Task::Task().
 {
   if(t.empty()) return false;
   for(auto c : t) {
     if(not (isalnum(c) || c == ' ' || c == '_') )
       return false;
   }
   return true;
 }